#!/bin/bash

#Plays battle music. uncomment while loop at own risk

introtune=$(./beepgen $(./timing.sh pokemon/VictoryTrainerIntro))
looptune=$(./beepgen $(./timing.sh  pokemon/VictoryTrainerMain))

beep $introtune
#while true
#do
    beep $looptune
    beep $looptune
#done
