#!/bin/bash

#Plays battle music. uncomment while loop at own risk

introtune=$(./beepgen $(./timing.sh pokemon/VictoryWildIntro))
looptune=$(./beepgen $(./timing.sh  pokemon/VictoryWildLoop))

beep $introtune
#while true
#do
    beep $looptune
    beep $looptune
#done
